### PR TITLE
🐛 Fix URL provider

### PR DESCRIPTION
**Pull request by nwingt**

### CODE REVIEW

**Comment by williamchong** [comment]
??? what does that do

**Review by nnkken — COMMENTED** [review]
The change seems weird to me...
The original logic is to find the first URL / text / image, so the `if` block after the enumeration will be exclusive and the order doesn't matters.
But with current changes, it will record URL / text but not stop enumeration until getting an image.
Which means:
 - `urlProvider` and `textProvider` will be the last URL / text before the first image, which sounds weird
 - The providers are not exclusive anymore, therefore it now has a priority order of `URL > image > text`

**Comment by nwingt** [comment]
I have referenced 2 forks of the original repo

https://github.com/RocketChat/rn-extensions-share/commit/265bee9905a7760e412ccee13c65cc93e2efd86c

https://github.com/jvandenaardweg/react-native-share-extension/commit/82d8c6515abcc29fae3e0c3bfcb55bce394989d3#diff-cd365a662ae840f4beb6a01a1c8ffa1f

The issue only happens if the attachments contain both URL & text

**Comment by williamchong** [comment]
Then we basically just want `URL_IDENTIFIER` to stop. why is the URL stop removed but the image was kept?

**Comment by nwingt** [comment]
@williamchong007 Just removed stop for text only

**Review by williamchong — APPROVED** [review]

**Pull request merged**
